### ISSUE TITLE
es.yml was giving errors on Outputs

### ISSUE THREAD

**Issue by jbird-fmr** [blend/log-pipeline#5]
I had errors with the es.yml CFT.
Error:

`An error occurred (ValidationError) when calling the CreateStack operation: Template error: resource ElasticsearchDomain does not support attribute type Endpoint in Fn::GetAtt`

This update worked for me:
Outputs:

  ```
ElasticseachDomainEndpoint:
    Description: The endpoint of the Elasticsearch Domain.
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint

  ElasticsearchDomainArn:
    Description: The ARN of the Elasticsearch Domain.
    Value: !GetAtt ElasticsearchDomain.DomainArn
```
